export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  readTime: string;
  sections: { heading: string; paragraphs?: string[]; bullets?: string[] }[];
};

export const posts: BlogPost[] = [
  { slug: "stripe-fees-calculator-guide", eyebrow: "Calculator guide", readTime: "8 min read", title: "Stripe Fees Calculator: See Your Net Payout Before You Charge", description: "A practical guide to calculating Stripe processing fees, reverse pricing, international cards, refunds, and the amount that actually reaches your bank.", sections: [
    { heading: "The number most businesses actually need", paragraphs: ["Stripe fees are easy to describe and surprisingly easy to misread. The headline rate is only one part of the calculation: a percentage applies to the payment amount and a fixed fee applies to every successful transaction.", "The useful result is not just the fee. It is the net payout, the effective fee percentage, and—when you are pricing a product—the amount you need to charge to receive a target amount after fees."] },
    { heading: "How the standard calculation works", paragraphs: ["For a standard US card example, the calculation is 2.9% of the charge plus $0.30. A $100 payment produces a $3.20 fee and a $96.80 net before any other adjustments.", "Rates can vary by country, card origin, payment method, contract, and account configuration. Use your Stripe pricing agreement for final accounting decisions; use a calculator to model the payment scenarios you care about."] },
    { heading: "Calculate the price needed to receive a target amount", paragraphs: ["Reverse pricing answers a different question: “If I need to receive $100, what should I charge?” The formula is (target amount + fixed fee) ÷ (1 − percentage rate). At 2.9% + $0.30, receiving exactly $100 requires a charge of about $103.09.", "This is useful for invoices, service packages, and checkout prices where the business—not the customer—is absorbing processing costs."] },
    { heading: "Do not forget international cards and refunds", bullets: ["International cards can add a separate cross-border surcharge.", "Currency conversion can add another fee when the payment currency and settlement currency differ.", "Refunds return the customer’s payment, but the original processing fee may not be returned.", "Disputes and chargebacks should be reviewed separately from normal payment fees."] },
    { heading: "How to use the calculator", bullets: ["Enter the amount you plan to charge, or switch to the amount you want to receive.", "Choose the card/payment scenario that best matches the transaction.", "Review the fee, net payout, and effective percentage.", "Optionally add your monthly transaction count to estimate total processing cost.", "Use the result to price the offer, reconcile the payout, or compare payment methods."] },
    { heading: "Keep the result connected to your books", paragraphs: ["For bookkeeping, gross revenue, processing fees, refunds, and the net payout can have different accounting treatments. When you export Stripe activity to QuickBooks, preserve the transaction IDs and review the net deposit against the bank feed.", "The calculator helps you plan the numbers. The Stripe2QB converter helps you move the export into a reviewable QuickBooks-ready CSV."] },
  ] },
  { slug: "how-to-export-stripe-to-quickbooks", eyebrow: "Workflow guide", readTime: "6 min read", title: "How to Export Stripe Transactions to QuickBooks", description: "A practical monthly workflow for exporting Stripe activity, preparing the right numbers, and importing cleanly into QuickBooks.", sections: [
    { heading: "Start with the right Stripe report", paragraphs: ["For a monthly close, begin in Stripe Dashboard → Reports → Balance. Set the same period you use for your bank reconciliation, then export the balance activity as CSV.", "Before editing anything, save an untouched copy. Your original export is the audit trail; your cleaned file is the import file."] },
    { heading: "Use net deposits for bank matching", paragraphs: ["Gross payments are what customers paid. Net is what Stripe actually settled after fees, refunds, and adjustments. If you are matching the Stripe payout to a bank feed, net is usually the number that should land in the deposit column.", "Keep gross and fees available for reporting, but do not accidentally book gross revenue as the bank deposit."] },
    { heading: "Clean only what QuickBooks needs", bullets: ["Date: convert Created (UTC) into MM/DD/YYYY.", "Description: keep a useful customer, invoice, or payment reference.", "Amount: use the net amount for a simple deposit import.", "Transaction ID: preserve it so duplicates can be investigated later."], paragraphs: ["Avoid deleting the source export’s extra columns until the import has been reviewed and accepted."] },
    { heading: "A repeatable monthly checklist", bullets: ["Export the period from Stripe and archive the original.", "Convert or clean the file using one consistent mapping.", "Review refunds, disputes, missing dates, and multiple currencies.", "Import into QuickBooks, then match the resulting deposit to the bank feed."] },
  ] },
  { slug: "stripe-fees-explained", eyebrow: "Payments basics", readTime: "5 min read", title: "Stripe Fees Explained: What Actually Gets Deducted", description: "Understand gross volume, processing fees, refunds, and net payout so your Stripe numbers make sense in your books.", sections: [
    { heading: "Gross, fee, and net are three different numbers", paragraphs: ["On a $100 card payment, gross is $100. The processing fee is the amount Stripe retains. Net is what remains after the fee and is the amount most closely related to a settlement.", "The exact rate depends on your country, payment method, contract, and account configuration. Treat examples as a way to understand the math, not as a replacement for your Stripe pricing page."] },
    { heading: "Why the fixed fee matters", paragraphs: ["A percentage fee has the same margin impact at every ticket size. A fixed fee does not: it takes a much larger share of a $10 payment than a $100 payment. That is why small-ticket businesses should model effective fee percentage, not just the advertised rate."] },
    { heading: "International and currency costs", paragraphs: ["International cards and currency conversion can add separate charges. Keep currency in your export and group your review by currency rather than combining everything into one total.", "For multi-currency accounts, reconcile each currency and settlement account separately whenever possible."] },
    { heading: "Book fees as a cost of payment", bullets: ["Revenue records the customer-facing sale.", "Processing fees belong in a payment-processing expense account.", "The payout or bank deposit is the net amount.", "Refunds and disputes should remain visible rather than being silently netted away."] },
  ] },
  { slug: "what-is-qbo-file-quickbooks", eyebrow: "File formats", readTime: "4 min read", title: "What Is a .QBO File and When Should You Use One?", description: "A plain-English guide to QBO files, CSV imports, bank feeds, and the safest format for Stripe-related bookkeeping.", sections: [
    { heading: "QBO is a bank-feed format", paragraphs: ["A .QBO file is an OFX-based bank statement format designed for QuickBooks bank activity. It carries statement metadata, transaction dates, amounts, memos, and unique IDs in a structure QuickBooks can read.", "A CSV is a general-purpose table. It is easier to inspect, but it usually requires column mapping and more decisions during import."] },
    { heading: "QBO is not automatically better for Stripe", paragraphs: ["Stripe exports do not represent a traditional bank account in every workflow. Payments, fees, refunds, disputes, and payouts can have different accounting meanings. Wrapping raw Stripe rows in a QBO file without understanding that structure can create misleading bank activity.", "For many Stripe-to-QuickBooks workflows, a clean CSV with explicit mapping is easier to audit than a synthetic bank statement."] },
    { heading: "Choose the format by the job", bullets: ["Use QBO when you are importing a genuine bank or processor statement.", "Use CSV when you need to inspect, transform, or map transaction data.", "Use a converter when date, fee, net, and refund handling need to be repeated.", "Always compare the imported total to the processor payout and bank deposit."] },
    { heading: "The reconciliation test", paragraphs: ["Whatever format you choose, the final test is simple: the imported activity should explain the amount that reached the bank. If it does not, stop and investigate before categorizing dozens of rows."] },
  ] },
  { slug: "stripe-vs-paypal-which-is-cheaper", eyebrow: "Cost comparison", readTime: "7 min read", title: "Stripe vs PayPal: Which Is Cheaper for Small Businesses?", description: "Compare payment costs the useful way: effective rate, average ticket, international mix, conversion, and reconciliation effort.", sections: [
    { heading: "Start with your actual payment mix", paragraphs: ["Headline pricing is only a starting point. Build a simple monthly model using your average order value, transaction count, international share, currency conversions, refunds, and payment methods.", "A provider with a higher fee can still be the better commercial choice if it converts more customers or saves meaningful manual work."] },
    { heading: "The small-ticket effect", paragraphs: ["Fixed fees matter. On a $20 payment, a $0.30 fixed charge is a much larger percentage than on a $200 payment. Compare both providers using your real average order value instead of a round $100 example."] },
    { heading: "Include operational cost", bullets: ["How long does each provider take to reconcile?", "How often do refunds or disputes need manual review?", "Do customers abandon checkout when their preferred wallet is missing?", "Can your accounting workflow separate gross, fees, and net cleanly?"] },
    { heading: "A decision that survives the spreadsheet", paragraphs: ["Calculate total monthly cost, then add a conservative value for conversion and operations. Revisit the model after a quarter of real data. The cheapest rate on paper is not always the cheapest system to run."] },
  ] },
  { slug: "why-quickbooks-wont-accept-my-stripe-csv", eyebrow: "Troubleshooting", readTime: "6 min read", title: "Why QuickBooks Won't Accept My Stripe CSV", description: "The five common reasons a Stripe export fails in QuickBooks—and a cleaner way to prepare the file.", sections: [
    { heading: "Stripe and QuickBooks use different schemas", paragraphs: ["A Stripe export is a processor report. QuickBooks import fields are designed around accounting and bank activity. The file can be perfectly valid and still fail because the columns, dates, signs, or totals do not match what QuickBooks expects."] },
    { heading: "The five checks that solve most failures", bullets: ["Convert UTC timestamps into a plain date format.", "Map Created (UTC), Description, and Net into the fields you actually import.", "Check whether the import should use gross, net, or separate fee lines.", "Review refunds, disputes, and negative amounts before uploading.", "Separate currencies when your QuickBooks setup requires it."] },
    { heading: "Validate before importing", paragraphs: ["Open the first and last few rows, check the total, and look for blank dates or amounts. A two-minute review is cheaper than undoing a large import.", "Our converter keeps the transformation local and flags common warnings so you can review before downloading the QuickBooks CSV."] },
  ] },
];
