import type { Metadata } from "next";
import Script from "next/script";
import ToolLayout from "@/components/ToolLayout";
import StripeVsSquareClient from "./StripeVsSquareClient";
import { FaqSchema } from "@/components/FaqSchema";

export const metadata: Metadata = { title: "Stripe Fees vs Square Calculator — Compare Costs", description: "Compare Stripe and Square processing fees for online payments. Enter your transaction amount and monthly volume to estimate which costs less.", keywords: ["stripe fees vs square", "stripe vs square fees", "stripe square fee calculator"], alternates: { canonical: "https://stripe-qb-converter.vercel.app/tools/stripe-fees-vs-square" }, openGraph: { title: "Stripe Fees vs Square Calculator", description: "Compare estimated Stripe and Square fees side by side." } };
const faqs = [{ q: "Is Stripe cheaper than Square?", a: "It depends on how you accept payments. The example online rates on this tool use Stripe at 2.9% + $0.30 and Square online at 3.3% + $0.30. Square Online API pricing can be different, so select the payment type that matches your setup." }, { q: "Does Square have a monthly fee?", a: "Square offers plans with different subscription and processing costs. This calculator compares processing fees only, so include any software or location subscription in your own total-cost comparison." }, { q: "Do the rates change by country?", a: "Yes. Stripe and Square pricing varies by country, payment method, plan, card origin, and custom pricing. Use this tool as an estimate and verify the current rate for your account." }];
const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "Stripe Fees vs Square Calculator", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } };
export default function StripeVsSquarePage() { return <><FaqSchema faqs={faqs} /><Script id="square-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><ToolLayout title="Stripe Fees vs Square" description="Compare estimated processing fees for Stripe and Square using your transaction amount and monthly volume." faqs={faqs}><StripeVsSquareClient /></ToolLayout></>; }
