"use client";

import { useCallback, useRef, useState } from "react";
import Papa from "papaparse";
import * as XLSX from "xlsx";

type QuickBooksRow = { Date: string; Description: string; Amount: string; Fee: string; Net: string; Customer: string; "Transaction ID": string };
type ConversionResult = { url: string; count: number; warnings: string[] };
type Status = "idle" | "processing" | "success" | "error";
const ACCEPTED_EXTENSIONS = [".csv", ".tsv", ".xlsx", ".xls", ".json"];
const ACCEPTED_LABEL = ".csv, .tsv, .xlsx, .xls, or .json";
function getExtension(name: string) { return name.slice(name.lastIndexOf(".")).toLowerCase(); }
function formatDate(value: string) { if (!value) return ""; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return `${String(date.getMonth() + 1).padStart(2, "0")}/${String(date.getDate()).padStart(2, "0")}/${date.getFullYear()}`; }
function amountInDollars(value: string | number) { const number = typeof value === "number" ? value : Number.parseFloat(value); return (Number.isFinite(number) ? number / 100 : 0).toFixed(2); }
function first(row: Record<string, string>, keys: string[]) { for (const key of keys) if (row[key]?.trim()) return row[key].trim(); return ""; }
function findEmail(row: Record<string, string>) { const preferred = first(row, ["Customer Email", "Customer email", "customer_email", "email"]); if (preferred.includes("@")) return preferred; return Object.values(row).find((value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) ?? ""; }
function parseCSV(text: string, delimiter?: string) { const parsed = Papa.parse<string[]>(text, { header: false, skipEmptyLines: true, delimiter }); if (parsed.errors.length) throw new Error("We couldn’t read this file as a CSV. Check that it is a valid Stripe export."); if (parsed.data.length < 2) throw new Error("This file is empty or only contains column headers. Upload a Stripe export with at least one transaction."); const headers = parsed.data[0].map((header, index) => header.trim() || `Column ${index + 1}`); return parsed.data.slice(1).map((values) => Object.fromEntries(headers.map((header, index) => [header, (values[index] ?? "").trim()]))); }
function parseSpreadsheet(buffer: ArrayBuffer) { const workbook = XLSX.read(buffer, { type: "array" }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; if (!sheet) throw new Error("No worksheet was found in this Excel file."); return XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" }).map((row) => Object.fromEntries(Object.entries(row).map(([key, value]) => [key, String(value)]))); }
function parseJSON(text: string) { let data: unknown; try { data = JSON.parse(text); } catch { throw new Error("This JSON file is not valid. Export the file again and try once more."); } const rows = Array.isArray(data) ? data : (data as { data?: unknown[] })?.data; if (!Array.isArray(rows)) throw new Error("This JSON file must contain an array of Stripe transactions or a data array."); return rows.map((item) => Object.fromEntries(Object.entries(item as Record<string, unknown>).map(([key, value]) => [key, value == null ? "" : String(value)]))); }
function convertRows(rows: Record<string, string>[]): ConversionResult { if (!rows.length) throw new Error("No transactions were found in this file."); const warnings = new Set<string>(); const currencies = new Set<string>(); let missingAmount = 0; let missingDate = 0; let refundCount = 0; const output: QuickBooksRow[] = rows.map((row) => { const amountRaw = first(row, ["Amount", "amount"]); const feeRaw = first(row, ["Fee", "fee"]); const date = first(row, ["Created (UTC)", "created_utc", "created", "Date", "date"]); const description = first(row, ["Description", "description"]); const id = first(row, ["id", "ID", "Transaction ID"]); const currency = first(row, ["Currency", "currency"]).toUpperCase(); if (currency) currencies.add(currency); if (!amountRaw || !Number.isFinite(Number.parseFloat(amountRaw))) missingAmount += 1; if (!date) missingDate += 1; if (/refund|dispute|chargeback/i.test(`${description} ${first(row, ["Type", "type", "Status", "status"])}`) || Number.parseFloat(amountRaw) < 0) refundCount += 1; const amount = Number.parseFloat(amountInDollars(amountRaw)); const fee = Number.parseFloat(amountInDollars(feeRaw)); return { Date: formatDate(date), Description: description, Amount: amountInDollars(amountRaw), Fee: amountInDollars(feeRaw), Net: (amount - fee).toFixed(2), Customer: findEmail(row), "Transaction ID": id }; }); if (currencies.size > 1) warnings.add(`Multiple currencies detected (${[...currencies].join(", ")}). Confirm currency handling in QuickBooks.`); if (refundCount) warnings.add(`${refundCount} refund, dispute, or chargeback row${refundCount === 1 ? "" : "s"} may need manual review.`); if (missingAmount) warnings.add(`${missingAmount} row${missingAmount === 1 ? " is" : "s are"} missing a valid Amount and were converted to $0.00.`); if (missingDate) warnings.add(`${missingDate} row${missingDate === 1 ? " is" : "s are"} missing a date.`); if (!output.some((row) => row["Transaction ID"])) warnings.add("No transaction IDs were found. Review duplicates before importing."); const blob = new Blob([Papa.unparse(output)], { type: "text/csv;charset=utf-8" }); return { url: URL.createObjectURL(blob), count: output.length, warnings: [...warnings] }; }

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null); const [dragging, setDragging] = useState(false); const [status, setStatus] = useState<Status>("idle"); const [error, setError] = useState(""); const [result, setResult] = useState<ConversionResult | null>(null);
  const handleFile = useCallback((file: File | null) => { if (!file) return; const extension = getExtension(file.name); setError(""); setResult(null); setStatus("processing"); if (!ACCEPTED_EXTENSIONS.includes(extension)) { setStatus("error"); setError(`“${extension || file.name}” isn’t supported. Please choose ${ACCEPTED_LABEL}.`); return; } if (!file.size) { setStatus("error"); setError("This file is empty. Export your Stripe data again and upload the new file."); return; } const reader = new FileReader(); reader.onerror = () => { setStatus("error"); setError("We couldn’t read this file. Please try again or export a fresh Stripe file."); }; reader.onload = (event) => { try { const value = event.target?.result; const rows = extension === ".xlsx" || extension === ".xls" ? parseSpreadsheet(value as ArrayBuffer) : extension === ".json" ? parseJSON(value as string) : parseCSV(value as string, extension === ".tsv" ? "\t" : undefined); setResult(convertRows(rows)); setStatus("success"); } catch (conversionError) { setStatus("error"); setError(conversionError instanceof Error ? conversionError.message : "We couldn’t convert this file. Please check the format and try again."); } }; if (extension === ".xlsx" || extension === ".xls") reader.readAsArrayBuffer(file); else reader.readAsText(file); }, []);
  const reset = () => { if (result) URL.revokeObjectURL(result.url); setResult(null); setError(""); setStatus("idle"); };
  return <div className="site-shell">
    <section className="hero"><div className="hero-orbit" /><div className="container"><div className="eyebrow"><span className="status-dot" /> Free browser tool · No account needed</div><h1>Stripe data,<br /><em>made useful.</em></h1><p className="hero-copy">Turn a Stripe export into a clean QuickBooks-ready CSV in seconds. Private by design, with everything processed right here in your browser.</p><div className="hero-meta"><span>01 / Upload</span><span>02 / Convert</span><span>03 / Import</span></div></div></section>
    <main className="container main-content"><section className="converter-panel"><div className="panel-heading"><div><span className="section-label">01 — Start here</span><h2>Bring your Stripe export</h2></div><p>Supports {ACCEPTED_LABEL}</p></div><div className="upload-grid"><label onDrop={(event) => { event.preventDefault(); setDragging(false); handleFile(event.dataTransfer.files?.[0] ?? null); }} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} className={`dropzone ${dragging ? "is-dragging" : ""}`}><input ref={inputRef} type="file" accept={ACCEPTED_EXTENSIONS.join(",")} className="hidden-input" onChange={(event) => { handleFile(event.target.files?.[0] ?? null); event.target.value = ""; }} />{status === "processing" ? <><div className="spinner" /><strong>Reading your file…</strong><small>Everything is processed locally.</small></> : <><div className="upload-mark">↑</div><strong>{dragging ? "Drop it here" : "Drop your file here"}</strong><small>or <span>choose a file</span></small><small className="privacy-note">Your financial data never leaves this browser.</small></>}</label><div className="sample-card"><span className="card-kicker">TRY THE FLOW</span><h3>No export handy?</h3><p>Use a safe sample file to see the converter in action.</p><a href="/sample-stripe-export.csv" download>Download sample <span>↗</span></a></div></div>{error && <div role="alert" className="alert error">{error}</div>}{result && status === "success" && <div className="result-card"><div><span className="section-label green">READY TO GO</span><h3>{result.count.toLocaleString()} rows converted.</h3><p>Your QuickBooks CSV is ready to download.</p></div><a href={result.url} download="quickbooks_import.csv" className="download-button">Download CSV <span>↓</span></a>{result.warnings.length > 0 && <div className="alert warning"><strong>Worth a quick review</strong><ul>{result.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}<button type="button" onClick={reset} className="reset-button">Convert another file</button></div>}</section>
      <section className="demo-section"><div><span className="section-label">SEE IT IN ACTION</span><h2>From Stripe export<br />to books-ready CSV.</h2><p>Watch the full flow before you upload your own file. The conversion happens locally in your browser.</p></div><div className="video-frame"><video controls preload="metadata" poster="/logo.png"><source src="/demo-recording.mp4" type="video/mp4" />Your browser does not support embedded video.</video></div></section>
      <section className="steps"><div className="section-label">HOW IT WORKS</div><div className="steps-grid">{[["01", "Export from Stripe", "Download your payments export from Stripe Dashboard → Payments → Export."], ["02", "Drop it here", "We map dates, amounts, fees, customers, and IDs in your browser."], ["03", "Import into QuickBooks", "Download the finished CSV and upload it through QuickBooks Banking."]].map(([number, title, description]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
      <section className="privacy-strip"><div><span className="section-label">BUILT FOR TRUST</span><h2>Your books stay yours.</h2></div><p>Stripe2QB runs entirely on your device. Nothing is uploaded, stored, or sent to a server. Close the tab and your data is gone.</p><div className="privacy-badge">LOCAL ONLY <span>✦</span></div></section>
      <section className="tools-section"><div className="panel-heading"><div><span className="section-label">MORE FROM STRIPE2QB</span><h2>Useful tools, no fluff.</h2></div><a href="/tools">View all tools ↗</a></div><div className="tools-grid">{[["Stripe fee calculator", "/tools/stripe-fee-calculator", "Know exactly what Stripe takes."], ["Payout calculator", "/tools/stripe-payout-calculator", "See your net payout at a glance."], ["Import error checker", "/tools/quickbooks-import-error-checker", "Catch CSV issues before QuickBooks does."], ["Revenue forecaster", "/tools/stripe-revenue-forecaster", "Plan ahead from your current MRR."]].map(([title, href, description], index) => <a key={href} href={href} className="tool-card"><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p><b>Explore ↗</b></a>)}</div></section>
    </main><footer><div className="container footer-inner"><span>Stripe2QB</span><span>Free, private, browser-based conversion.</span><span>© 2026</span></div></footer>
  </div>;
}
