"use client";

import { useState } from "react";

const regions = ["United States", "Canada", "Australia", "New Zealand", "United Kingdom", "Other"];
export default function NonprofitPricingClient() {
  const [region, setRegion] = useState("United States");
  const [donationShare, setDonationShare] = useState("80");
  const eligibleRegion = regions.slice(0, -1).includes(region);
  const likelyEligible = eligibleRegion && Number(donationShare) >= 80;
  return <div className="space-y-6"><label className="block text-sm font-medium text-gray-700">Where is your nonprofit registered?<select value={region} onChange={(e) => setRegion(e.target.value)} className="mt-2 w-full rounded-lg border border-gray-300 bg-white px-4 py-3">{regions.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-sm font-medium text-gray-700">What percentage of payment volume is tax-deductible donations?<input value={donationShare} onChange={(e) => setDonationShare(e.target.value.replace(/\D/g, ""))} inputMode="numeric" className="mt-2 w-full rounded-lg border border-gray-300 px-4 py-3" /><span className="mt-2 block text-xs font-normal text-gray-500">Stripe’s published eligibility guidance uses an 80% donation-volume threshold.</span></label><div className={`rounded-xl border p-5 ${likelyEligible ? "border-green-200 bg-green-50" : "border-amber-200 bg-amber-50"}`}><p className="font-semibold text-gray-900">{likelyEligible ? "You may qualify to request nonprofit pricing" : "You may not qualify based on these answers"}</p><p className="mt-2 text-sm leading-relaxed text-gray-600">{likelyEligible ? "You appear to meet the region and donation-volume checks. Stripe still reviews your nonprofit registration and tax documentation before enabling any discount." : "Stripe nonprofit pricing is limited to eligible regions and accounts primarily used for tax-deductible donations. Review the official eligibility requirements before applying."}</p></div><div className="rounded-lg bg-gray-50 p-4 text-sm leading-relaxed text-gray-600"><strong className="text-gray-900">Important:</strong> Stripe does not publish one universal nonprofit rate in this guidance. The discount must be requested through Stripe support and approved for the account. This tool is an eligibility pre-check, not a guaranteed quote.</div><a href="https://support.stripe.com/questions/fee-discount-for-nonprofit-organizations" target="_blank" rel="noreferrer" className="inline-block rounded-lg bg-indigo-600 px-4 py-3 text-sm font-semibold text-white hover:bg-indigo-700">Review Stripe’s requirements ↗</a></div>;
}
