import type { Metadata } from "next";
import Script from "next/script";
import ToolLayout from "@/components/ToolLayout";
import NonprofitPricingClient from "./NonprofitPricingClient";
import { FaqSchema } from "@/components/FaqSchema";

export const metadata: Metadata = { title: "Stripe Nonprofit Pricing Checker — Eligibility Guide", description: "Check whether your nonprofit may meet Stripe’s published region and donation-volume requirements for discounted processing fees. Free eligibility tool.", keywords: ["stripe nonprofit pricing", "stripe nonprofit fees", "stripe charity fees", "stripe donation fees"], alternates: { canonical: "https://stripe-qb-converter.vercel.app/tools/stripe-nonprofit-pricing" }, openGraph: { title: "Stripe Nonprofit Pricing Eligibility Checker", description: "Check the basic requirements before requesting Stripe nonprofit pricing." } };
const faqs = [{ q: "Does Stripe offer nonprofit pricing?", a: "Stripe offers discounted processing fees to eligible nonprofit organisations that primarily accept tax-deductible donations in supported regions. Approval is handled by Stripe." }, { q: "What donation percentage is required?", a: "Stripe’s published support guidance says at least 80% of payment volume must come from tax-deductible donations. Memberships, tuition, tickets, registration fees, and auctions do not count toward that threshold." }, { q: "Does this tool guarantee a nonprofit discount?", a: "No. It is an eligibility pre-check. Stripe must review the organisation’s registration, tax documentation, account details, and donation mix before enabling any nonprofit pricing." }];
const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "Stripe Nonprofit Pricing Checker", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } };
export default function StripeNonprofitPricingPage() { return <><FaqSchema faqs={faqs} /><Script id="nonprofit-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><ToolLayout title="Stripe Nonprofit Pricing Checker" description="Check the basic eligibility signals before applying for Stripe’s nonprofit processing discount." faqs={faqs}><NonprofitPricingClient /></ToolLayout></>; }
